# Use official Python image
FROM python:3.9  

# Set the working directory
WORKDIR /app  

# Copy application files
COPY requirements.txt requirements.txt  
COPY app.py app.py  

# Install dependencies
RUN pip install -r requirements.txt  

# Expose the port Flask runs on
EXPOSE 5000  

# Command to run the app
CMD ["python", "app.py"]
